# Update dependencies with Dependabot

version: 2
updates:
  # Set update schedule for Ruby Bundler
  - package-ecosystem: "bundler"
    # Raise pull requests to update vendored dependencies that are checked in to the repository
    vendor: true
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignoring binding_of_caller 1.0 temporarily until we find a solution for it breaking Docker
      # see <https://github.com/forem/forem/issues/12068>
      - dependency-name: "binding_of_caller"
        versions: [">= 1.0"]
    labels: []

  # Set update schedule for Yarn/NPM
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []

  # Set update schedule for GitHub Actions
  # https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
