experiments:
  # No field test running.
  # To run a test, change the five variants here. You can create more than
  # five, but five is our typical standard.
  # Do not change the goals unless you intend to also change the corresponding code in
  # app/workers/users/record_field_test_event_worker.rb

  feed_strategy_round_4:
    variants:
      - original
      - final_order_by_score
      - final_order_by_comment_score
      - final_order_by_last_comment_at
      - final_order_by_random
      - final_order_by_random_weighted_to_score
      - final_order_by_random_weighted_to_comment_score
      - final_order_by_random_weighted_to_last_comment_at
    weights:
      - 51
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
    goals:
      - user_creates_comment
      - user_creates_comment_four_days_in_week
      - user_views_article_four_days_in_week
      - user_views_article_four_hours_in_day
      - user_views_article_nine_days_in_two_week
      - user_views_article_twelve_hours_in_five_days


exclude:
  bots: true

# Dashboard performance
cache: true
precision: 2

# For logged-in users we'll explicitly pass participant.
# If we experiment on non-logged in, we don't want to collect cookies anyway.
cookies: false
