---
like:
  position: 1
  name: Like
  icon: sparkle-heart
unicorn:
  position: 2
  name: Babel
  icon: babel-filled
# exploding_head:
#   position: 3
#   name: Exploding Head
#   icon: exploding-head
# raised_hands:
#   position: 4
#   name: Raised Hands
#   icon: raised-hands
# fire:
#   position: 5
#   name: Fire
#   icon: fire
k30:
  position: 3
  name: K30
  icon: katsu_30.png
roman:
  position: 4
  name: Roman
  icon: roman
readinglist:
  # position: 5
  icon: save
  published: false
thumbsup:
  privileged: true
  score: 5.0
thumbsdown:
  privileged: true
  score: -10.0
vomit:
  privileged: true
  name: Vomit
  score: -50.0
thinking:
  published: false
hands:
  published: false
